### ISSUE TITLE
Run flask in production mode

### ISSUE THREAD

**Issue by berndbohmeier** [trustlines-protocol/merkle-drop#37]
Choose and use a wsgi runner like uWSGI or gunicorn to run flask in production.

**Comment by jondoe1337** [comment]
Okay seems to be working without any changes:

```
[mschmidt@honeypot][~/git/brainbot/merkle-drop]
$ gunicorn --bind 127.0.0.1:4000 merkle_drop.server:app
```

Is there anything more to check @berndbohmeier @schmir-at-bb ?

**Comment by berndbohmeier** [comment]
I dont think so.

**Comment by schmir-at-bb** [comment]
You want to make sure that the merkle tree initialization is only done once in the parent process. The forked child processes will then not have to do the initialization on their own.

**Comment by jondoe1337** [comment]
As requested and discussed with @schmir-at-bb I will add documentation and a config file for gunicorn that enforces the loading of tree in the once parent (and passes it to the forked childs)
